development:
  debug_mode: true
  profile: false
  runtime: 1440
  display_logs_in_console: false
  output_directory: "data/2024-11-20_10_42_39-supine"

logging:
  mcts_report_fraction: 0
  gpu_evaluation: true
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 128

  # Number of games to accumulate before they're flushed to disk.
  # Very large value here so we don't save the games.
  game_flush_threshold: 1.0e+9

networks:
  default:
    main_body_channels: 64
    value_head_channels: 16
    value_head_flat_layer_width: 64
    policy_head_channels: 64
    residual_blocks: 8

    model_path: "data/2024-11-20_10_42_39-supine/model/2024-11-20_09-34-23_478500.pt"

    batch_size: 64

    # Frequency to check if there's a new model to load from disk.
    # Very large value here so we don't worry about loading new models.
    new_model_check_interval: 1.0e+9

training:
  run: false

default_agent:
  mcts:
    network: "default"
    full_move_probability: 1.0
    full_move_rollouts: 500
    fast_move_rollouts: "never used"
    ucb_exploration: 1.4
    total_dirichlet_alpha: 10.83
    root_exploration_fraction: "placeholder to override"

individual_agents:
  - name: "root_exploration_fraction_0"
    mcts:
      root_exploration_fraction: 0.0
  - name: "root_exploration_fraction_08"
    mcts:
      root_exploration_fraction: 0.08
  - name: "root_exploration_fraction_16"
    mcts:
      root_exploration_fraction: 0.16
  - name: "root_exploration_fraction_25"
    mcts:
      root_exploration_fraction: 0.25