development:
  debug_mode: true
  profile: false
  runtime: 3600
  display_logs_in_console: false
  output_directory: "data/2024-12-08_00-11-50-arena-for-retrained-sampling-ratio-one-vs-two-with-literatist"

logging:
  save_interval: 120
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: false
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  num_pieces: 21
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 256
  game_flush_threshold: 10

default_network:
  main_body_channels: 64
  value_head_channels: 16
  value_head_flat_layer_width: 64
  policy_head_channels: 64
  residual_blocks: 8
  batch_size: "overwritten"
  new_model_check_interval: -1

individual_networks:
  one:
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-02_21-22-57-notebook-models/base_in_notebook_1.pt"
    batch_size: 32
  two:
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-02_21-22-57-notebook-models/sample_ratio_two_1.pt"
    batch_size: 32
  literatist:
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-24_00-18-45-literatist/models/001720035.pt"
    batch_size: 64

training:
  run: false

default_agent:
  type: "mcts"
  network: "override"
  full_move_probability: 1.0
  full_move_rollouts: 500
  fast_move_rollouts: "never used"
  ucb_exploration: 1.4
  total_dirichlet_alpha: 10.83
  root_exploration_fraction: 0.0
  move_selection_temperature: 1.0

individual_agents:
  - name: "one"
    network: "one"
    move_selection_temperature: 0.3
  - name: "two"
    network: "two"
    move_selection_temperature: 0.3    
  - name: "literatist"
    network: "literatist"
    move_selection_temperature: 1.0
  - name: "literatist"
    network: "literatist"
    move_selection_temperature: 1.0
