development:
  debug_mode: true
  profile: false
  runtime: 3600
  display_logs_in_console: false
  output_directory: "data/2024-11-24_22-29-42-arena-for-doublehandedness-vs-literatist"

logging:
  save_interval: 120
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: true
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 128

  # Number of games to accumulate before they're flushed to disk.
  # Very large value here so we don't save the games.
  game_flush_threshold: 1.0e+9

default_network:
  main_body_channels: 64
  value_head_channels: 16
  value_head_flat_layer_width: 64
  policy_head_channels: 64
  residual_blocks: 8
  batch_size: 16
  # Frequency to check if there's a new model to load from disk.
  # Very large value here so we don't worry about loading new models.
  new_model_check_interval: 1.0e+9  

individual_networks:
  literatist_642275:
    model_path: "data/2024-11-24_00-18-45-literatist/models/000642275.pt"

  literatist_548823:
    model_path: "data/2024-11-24_00-18-45-literatist/models/000548823.pt"

  doublehandedness_642415:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/000642415.pt"

  doublehandedness_548878:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/000548878.pt"

training:
  run: false

default_agent:
  type: "mcts"
  network: "placeholder to override"
  full_move_probability: 1.0
  full_move_rollouts: 500
  fast_move_rollouts: "never used"
  ucb_exploration: 1.4
  total_dirichlet_alpha: 10.83
  root_exploration_fraction: 0.08

individual_agents:
  - name: "literatist_642275"
    network: "literatist_642275"
  - name: "literatist_548823"
    network: "literatist_548823"
  - name: "doublehandedness_642415"
    network: "doublehandedness_642415"
  - name: "doublehandedness_548878"
    network: "doublehandedness_548878"
