development:
  debug_mode: true
  profile: false
  runtime: 3600
  display_logs_in_console: false
  output_directory: "data/2024-11-21_16-37-53-medicinal"

logging:
  save_interval: 120
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: true
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 128

  # Number of games to accumulate before they're flushed to disk.
  # Very large value here so we don't save the games.
  game_flush_threshold: 1.0e+9

networks:
  s127919:
    main_body_channels: 64
    value_head_channels: 16
    value_head_flat_layer_width: 64
    policy_head_channels: 64
    residual_blocks: 8

    model_path: "data/2024-11-20_23-29-01-chickpea/models/2024-11-21_02-02-07_101650.pt"

    batch_size: 16

    # Frequency to check if there's a new model to load from disk.
    # Very large value here so we don't worry about loading new models.
    new_model_check_interval: 1.0e+9

  s253555:
    main_body_channels: 64
    value_head_channels: 16
    value_head_flat_layer_width: 64
    policy_head_channels: 64
    residual_blocks: 8

    model_path: "data/2024-11-20_23-29-01-chickpea/models/2024-11-21_04-31-02_093684.pt"

    batch_size: 16

    # Frequency to check if there's a new model to load from disk.
    # Very large value here so we don't worry about loading new models.
    new_model_check_interval: 1.0e+9

  s379394:
    main_body_channels: 64
    value_head_channels: 16
    value_head_flat_layer_width: 64
    policy_head_channels: 64
    residual_blocks: 8

    model_path: "data/2024-11-20_23-29-01-chickpea/models/2024-11-21_06-58-13_953337.pt"

    batch_size: 16

    # Frequency to check if there's a new model to load from disk.
    # Very large value here so we don't worry about loading new models.
    new_model_check_interval: 1.0e+9

  s510189:
    main_body_channels: 64
    value_head_channels: 16
    value_head_flat_layer_width: 64
    policy_head_channels: 64
    residual_blocks: 8

    model_path: "data/2024-11-20_23-29-01-chickpea/models/2024-11-21_09-30-12_240898.pt"

    batch_size: 16

    # Frequency to check if there's a new model to load from disk.
    # Very large value here so we don't worry about loading new models.
    new_model_check_interval: 1.0e+9        

training:
  run: false

default_agent:
  mcts:
    network: "placeholder to override"
    full_move_probability: 1.0
    full_move_rollouts: 500
    fast_move_rollouts: "never used"
    ucb_exploration: 1.4
    total_dirichlet_alpha: 10.83
    root_exploration_fraction: 0.08

individual_agents:
  - name: "s127919"
    mcts:
      network: "s127919"
  - name: "s253555"
    mcts:
      network: "s253555"
  - name: "s379394"
    mcts:
      network: "s379394"
  - name: "s510189"
    mcts:
      network: "s510189"