development:
  debug_mode: true
  profile: false
  runtime: 3600
  display_logs_in_console: false
  output_directory: "data/2024-12-10_18-41-43-arena-for-trained-ratio-1.0-vs-doublehandedness"

logging:
  save_interval: 120
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: false
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  num_pieces: 21
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 128
  game_flush_threshold: 1

default_network:
  main_body_channels: 64
  value_head_channels: 16
  value_head_flat_layer_width: 64
  policy_head_channels: 64
  residual_blocks: 8
  batch_size: 16
  new_model_check_interval: -1

individual_networks:
  weight_0158:
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-04_00-53-48-self-play-for-sampling-ratio-two/models/000520016.pt"
  weight_1000:
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-06_00-09-14-self-play-for-policy-weight-one/models/000520016.pt"
  dh:
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/002190002.pt"
    batch_size: 32    

training:
  run: false

default_agent:
  type: "mcts"
  network: "override"
  full_move_probability: 1.0
  full_move_rollouts: 500
  fast_move_rollouts: "never used"
  ucb_exploration: 1.4
  total_dirichlet_alpha: 10.83
  root_exploration_fraction: 0.0
  move_selection_temperature: "overwritten"

individual_agents:
  - name: "weight_0158"
    network: "weight_0158"
    move_selection_temperature: 0.3
  - name: "weight_1000"
    network: "weight_1000"
    move_selection_temperature: 0.3    
  - name: "dh"
    network: "dh"
    move_selection_temperature: 1.0    
  - name: "dh"
    network: "dh"
    move_selection_temperature: 1.0
