development:
  debug_mode: true
  profile: false
  runtime: 10800
  display_logs_in_console: false
  output_directory: "data/2024-12-03_19-34-40-arena-for-sample-rate-changes-on-policy-sample"

logging:
  save_interval: 120
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: false
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  num_pieces: 21
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 256
  game_flush_threshold: 200

default_network:
  model_path: "override this"
  main_body_channels: 64
  value_head_channels: 16
  value_head_flat_layer_width: 64
  policy_head_channels: 64
  residual_blocks: 8
  batch_size: 21
  new_model_check_interval: -1

individual_networks:
  "dh":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/002190002.pt"
  "base_in_notebook_1":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-02_21-22-57-notebook-models/base_in_notebook_1.pt"
  "base_in_notebook_2":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-02_21-22-57-notebook-models/base_in_notebook_2.pt"
  "base_in_notebook_3":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-02_21-22-57-notebook-models/base_in_notebook_3.pt"
  "sample_ratio_two_1":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-02_21-22-57-notebook-models/sample_ratio_two_1.pt"
  "sample_ratio_two_2":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-12-02_21-22-57-notebook-models/sample_ratio_two_2.pt"

training:
  run: false

# default_agent:
#   type: "mcts"
#   network: "placeholder to override"
#   full_move_probability: 1.0
#   full_move_rollouts: 500
#   fast_move_rollouts: "never used"
#   ucb_exploration: 1.4
#   total_dirichlet_alpha: 10.83
#   root_exploration_fraction: 0.0
#   move_selection_temperature: "override"

default_agent:
  type: "policy_sampling"
  network: "placeholder to override"
  move_selection_temperature: "override"

individual_agents:
  - name: "dh_temp0.3"
    move_selection_temperature: 0.3
    network: "dh"
  - name: "dh_temp1.0"
    move_selection_temperature: 1.0
    network: "dh"
  - name: "base_in_notebook_1_temp0.3"
    move_selection_temperature: 0.3
    network: "base_in_notebook_1"
  - name: "base_in_notebook_1_temp1.0"
    move_selection_temperature: 1.0
    network: "base_in_notebook_1"
  - name: "base_in_notebook_2_temp0.3"
    move_selection_temperature: 0.3
    network: "base_in_notebook_2"
  - name: "base_in_notebook_2_temp1.0"
    move_selection_temperature: 1.0
    network: "base_in_notebook_2"
  - name: "base_in_notebook_3_temp0.3"
    move_selection_temperature: 0.3
    network: "base_in_notebook_3"
  - name: "base_in_notebook_3_temp1.0"
    move_selection_temperature: 1.0
    network: "base_in_notebook_3"
  - name: "sample_ratio_two_1_temp0.3"
    move_selection_temperature: 0.3
    network: "sample_ratio_two_1"
  - name: "sample_ratio_two_1_temp1.0"
    move_selection_temperature: 1.0
    network: "sample_ratio_two_1"
  - name: "sample_ratio_two_2_temp0.3"
    move_selection_temperature: 0.3
    network: "sample_ratio_two_2"
  - name: "sample_ratio_two_2_temp1.0"
    move_selection_temperature: 1.0
    network: "sample_ratio_two_2"