development:
  debug_mode: true
  profile: false
  runtime: 10800
  display_logs_in_console: false
  output_directory: "data/2024-12-01_10-23-12-giant-arena-for-doublehandedness"

logging:
  save_interval: 120
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: true
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  num_pieces: 21
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 256
  game_flush_threshold: 200

default_network:
  model_path: "override this"
  main_body_channels: 64
  value_head_channels: 16
  value_head_flat_layer_width: 64
  policy_head_channels: 64
  residual_blocks: 8
  batch_size: 12

  # Very large value so we don't check for new models.
  new_model_check_interval: 1.0e+6

individual_networks:
  "204325":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/000204325.pt"
  "403006":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/000403006.pt"
  "808640":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/000808640.pt"
  "1005949":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001005949.pt"
  "1110265":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001110265.pt"
  "1204743":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001204743.pt"
  "1309389":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001309389.pt"
  "1400050":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001400050.pt"
  "1500018":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001500018.pt"
  "1600050":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001600050.pt"
  "1700018":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001700018.pt"
  "1800050":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001800050.pt"
  "1900018":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/001900018.pt"
  "2000050":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/002000050.pt"
  "2100018":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/002100018.pt"
  "2190002":
    model_path: "/Users/shivamsarodia/Dev/blockus/data/2024-11-23_00-37-50-doublehandedness/models/002190002.pt"

training:
  run: false

default_agent:
  type: "mcts"
  network: "placeholder to override"
  full_move_probability: 1.0
  full_move_rollouts: 500
  fast_move_rollouts: "never used"
  ucb_exploration: 1.4
  total_dirichlet_alpha: 10.83
  root_exploration_fraction: 0.08

individual_agents:
  - name: "204325"
    network: "204325"
  - name: "403006"
    network: "403006"
  - name: "808640"
    network: "808640"
  - name: "1005949"
    network: "1005949"
  - name: "1110265"
    network: "1110265"
  - name: "1204743"
    network: "1204743"
  - name: "1309389"
    network: "1309389"
  - name: "1400050"
    network: "1400050"
  - name: "1500018"
    network: "1500018"
  - name: "1600050"
    network: "1600050"
  - name: "1700018"
    network: "1700018"
  - name: "1800050"
    network: "1800050"
  - name: "1900018"
    network: "1900018"
  - name: "2000050"
    network: "2000050"
  - name: "2100018"
    network: "2100018"
  - name: "2190002"
    network: "2190002"
