development:
  debug_mode: true
  profile: false
  runtime: 10800
  display_logs_in_console: false
  output_directory: "data/2024-11-27_19-07-37-meated"

logging:
  save_interval: 120
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: true
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 6
  coroutines_per_process: 256

  # Very large value here so we don't save the games.
  game_flush_threshold: 1.0e+6

default_network:
  model_path: "override this"
  main_body_channels: 64
  value_head_channels: 16
  value_head_flat_layer_width: 64
  policy_head_channels: 64
  residual_blocks: 8
  batch_size: 12

  # Very large value so we don't check for new models.
  new_model_check_interval: 1.0e+6

individual_networks:
  literatist_0900k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/000900003.pt"
  literatist_1000k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/001000035.pt"
  literatist_1100k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/001100003.pt"
  literatist_1150k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/001150051.pt"
  literatist_1200k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/001200035.pt"
  literatist_1250k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/001250019.pt"
  literatist_1300k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/001300003.pt"
  literatist_1350k:
    model_path: "data/2024-11-24_00-18-45-literatist/models/001350051.pt"
  doublehandedness_0900k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/000902125.pt"
  doublehandedness_1000k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/001005949.pt"
  doublehandedness_1100k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/001099850.pt"
  doublehandedness_1150k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/001152252.pt"
  doublehandedness_1200k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/001204743.pt"
  doublehandedness_1250k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/001246401.pt"
  doublehandedness_1300k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/001298961.pt"
  doublehandedness_1350k:
    model_path: "data/2024-11-23_00-37-50-doublehandedness/models/001350898.pt"

training:
  run: false

default_agent:
  type: "mcts"
  network: "placeholder to override"
  full_move_probability: 1.0
  full_move_rollouts: 500
  fast_move_rollouts: "never used"
  ucb_exploration: 1.4
  total_dirichlet_alpha: 10.83
  root_exploration_fraction: 0.08

individual_agents:
  - name: "literatist_0900k"
    network: "literatist_0900k"
  - name: "literatist_1000k"
    network: "literatist_1000k"
  - name: "literatist_1100k"
    network: "literatist_1100k"
  - name: "literatist_1150k"
    network: "literatist_1150k"
  - name: "literatist_1200k"
    network: "literatist_1200k"
  - name: "literatist_1250k"
    network: "literatist_1250k"
  - name: "literatist_1300k"
    network: "literatist_1300k"
  - name: "literatist_1350k"
    network: "literatist_1350k"
  - name: "doublehandedness_0900k"
    network: "doublehandedness_0900k"
  - name: "doublehandedness_1000k"
    network: "doublehandedness_1000k"
  - name: "doublehandedness_1100k"
    network: "doublehandedness_1100k"
  - name: "doublehandedness_1150k"
    network: "doublehandedness_1150k"
  - name: "doublehandedness_1200k"
    network: "doublehandedness_1200k"
  - name: "doublehandedness_1250k"
    network: "doublehandedness_1250k"
  - name: "doublehandedness_1300k"
    network: "doublehandedness_1300k"
  - name: "doublehandedness_1350k"
    network: "doublehandedness_1350k"

