development:
  debug_mode: true
  profile: false
  runtime: 36000
  display_logs_in_console: false
  output_directory: "data/2024-11-21_17-17-40-remicate"

logging:
  save_interval: 60
  mcts_report_fraction: 1.0
  ucb_report: true
  gpu_evaluation: true
  made_move: true

game:
  board_size: 10
  num_moves: 6233
  moves_directory: "data/moves_10/"

architecture:
  gameplay_processes: 1
  coroutines_per_process: 1
  game_flush_threshold: 1

networks:
  default:
    main_body_channels: 64
    value_head_channels: 16
    value_head_flat_layer_width: 64
    policy_head_channels: 64
    residual_blocks: 8

    batch_size: 1

    model_path: "data/2024-11-20_23-29-01-chickpea/models/2024-11-21_09-30-12_240898.pt"
    model_directory: ""
    new_model_check_interval: 1.0e+6

training:
  run: false

default_agent:
  mcts:
    network: "default"
    full_move_probability: 1.0
    full_move_rollouts: 500
    fast_move_rollouts: 100
    # Very haphazard guess at an exploration parameter.
    ucb_exploration: 1.4
    # This mimics the value in AlphaZero using the logic from KataGo.
    total_dirichlet_alpha: 10.83
    root_exploration_fraction: 0.25

individual_agents:
  - name: "default"
  - name: "default"
  - name: "default"
  - name: "default"