[development]
debug_mode = true
profile = false
runtime = 120
display_logs_in_console = false
output_directory = "data/"

[game]
board_size = 10
num_moves = 6233
moves_directory = "data/moves_10/"

[network]
main_body_channels = 64
value_head_channels = 16
value_head_flat_layer_width = 64
policy_head_channels = 64
residual_blocks = 8

[architecture]
gameplay_processes = 6
coroutines_per_process = 256
inference_batch_size = 128

[mcts]
full_move_probability = 0.2
full_move_rollouts = 500
fast_move_rollouts = 100
# Very haphazard guess at an exploration parameter.
ucb_exploration = 1.4
root_dirichlet_alpha = 0.03
root_exploration_fraction = 0.25
