[development]
debug_mode = true
profile = false
runtime = 10800
display_logs_in_console = false
output_directory = "data/"

[game]
board_size = 10
num_moves = 6233
moves_directory = "data/moves_10/"

[network]
main_body_channels = 64
value_head_channels = 16
value_head_flat_layer_width = 64
policy_head_channels = 64
residual_blocks = 8

[architecture]
gameplay_processes = 6
coroutines_per_process = 256
inference_batch_size = 128
inference_recent_cache_size = 0

[mcts]
num_rollouts = 500
# Very haphazard guess at an exploration parameter.
ucb_exploration = 1.4
# This is 0.25, because we assume that for an unexpanded child there's a 1/4 
# chance of winning from it.
ucb_default_child_value = 0.25
root_dirichlet_alpha = 0.03
root_exploration_fraction = 0.25
