development: 
  display_logs_in_console: true

logging:
  mcts_report_fraction: 0.0
  gpu_evaluation: false
  made_move: false

architecture:
  gameplay_processes: 1
  game_flush_threshold: 1

networks:
  default:
    new_model_check_interval: 10

training:
  new_data_check_interval: 10