development: 
  display_logs_in_console: true
  output_directory: "data/2024-11-22_18-45-57-jamie"

logging:
  save_interval: 1.0e+6
  mcts_report_fraction: 0
  ucb_report: false
  gpu_evaluation: false
  made_move: true

architecture:
  gameplay_processes: 1
  game_flush_threshold: 1

networks:
  default:
    new_model_check_interval: 10
    model_path: ""
    model_directory: "data/2024-11-22_18-45-57-jamie/models"

training:
  sample_window: 20
  samples_per_generation: 10
  sampling_ratio: 1.0
  sampling_delay: 5
  new_data_check_interval: 5
